theme: jekyll-theme-midnight
title: Welcome to Ryan Lafler's Homepage for the Fall 2021 Semester BDA-594 Course!
description: This site will host assignments, projects and coding examples related to topics in Big Data Analysis.
