theme: jekyll-theme-midnight
title: Welcome to Ryan Lafler's Homepage for the Fall 2021 semester course BDA-594!
description: This site will host assignments, projects and coding examples related to opics in Big Data Analysis.
